// Generated by CoffeeScript 1.4.0
(function() {

  jQuery(function() {
    var commentRoot, comment_pattern, comments, fa, rated_comments, score, topComments;
    comment_pattern = 'div.comment_item[id^="comment_"]';
    commentRoot = $('div.comments_list[id="comments"]');
    topComments = ($(commentRoot)).find('>' + comment_pattern);
    comments = $(comment_pattern);
    rated_comments = [];
    fa = comments[0];
    score = parseInt(($(fa)).find('.score').attr('title').split(':')[0].split(' ')[1]);
    return rated_comments.push({
      "comment": fa,
      "score": score
    });
  });

}).call(this);
