// Generated by CoffeeScript 1.4.0
(function() {
  var Parser;

  window.Parser = Parser = (function() {

    function Parser() {
      this.comments = [];
    }

    Parser.prototype.findComments = function(soup) {
      return soup;
    };

    return Parser;

  })();

}).call(this);
