// Generated by CoffeeScript 1.4.0
(function() {

  describe("Parser", function() {
    beforeEach(function() {
      this.parser = new Parser;
      return this.document = window.document;
    });
    return it("finds comments", function() {
      return (expect(this.parser.findComments(this.document))).toContain(this.document.head);
    });
  });

}).call(this);
